import shutil
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "tools"))

import generate_skill_reference as gen  # noqa: E402

import insitupy  # noqa: E402


@pytest.fixture
def generator(tmp_path, monkeypatch):
    """Point the generator's output paths at a scratch tree instead of the real repo files."""
    skill_dir = tmp_path / "skill"
    reference_dir = skill_dir / "reference"
    skill_md = skill_dir / "SKILL.md"
    llms_txt = tmp_path / "llms.txt"
    skill_dir.mkdir(parents=True)
    shutil.copy(gen.SKILL_MD, skill_md)

    monkeypatch.setattr(gen, "SKILL_DIR", skill_dir)
    monkeypatch.setattr(gen, "SKILL_MD", skill_md)
    monkeypatch.setattr(gen, "REFERENCE_DIR", reference_dir)
    monkeypatch.setattr(gen, "LLMS_TXT", llms_txt)
    return gen


def test_generate_writes_every_expected_reference_file(generator):
    generator.write_targets(insitupy.__version__)

    for filename in generator.RENDERERS:
        path = generator.REFERENCE_DIR / filename
        content = path.read_text(encoding="utf-8")
        assert content.strip(), f"{filename} is empty"
        assert "AUTO-GENERATED by tools/generate_skill_reference.py" in content

    pitfalls = generator.REFERENCE_DIR / "conventions_and_pitfalls.md"
    assert "AUTO-GENERATED by tools/generate_skill_reference.py" in pitfalls.read_text(
        encoding="utf-8"
    )
    assert generator.LLMS_TXT.read_text(encoding="utf-8").strip()


def test_stamps_installed_version_and_known_symbols_appear(generator):
    version = insitupy.__version__
    generator.write_targets(version)

    skill_text = generator.SKILL_MD.read_text(encoding="utf-8")
    assert f'version: "{version}"' in skill_text

    io_formats = (generator.REFERENCE_DIR / "io_formats.md").read_text(encoding="utf-8")
    assert "read_xenium" in io_formats


def test_check_symbols_passes_against_the_real_installed_api():
    assert gen.check_symbols() == 0


def test_check_symbols_fails_when_a_curated_symbol_is_missing(monkeypatch):
    monkeypatch.setattr(
        gen,
        "CURATED_SYMBOLS",
        gen.CURATED_SYMBOLS + ("insitupy.pp.this_function_does_not_exist",),
    )
    assert gen.check_symbols() != 0


def test_check_reports_no_drift_immediately_after_generate(generator):
    version = insitupy.__version__
    generator.write_targets(version)
    assert generator.check_drift(version) == 0


def test_check_detects_content_drift(generator):
    version = insitupy.__version__
    generator.write_targets(version)

    target = generator.REFERENCE_DIR / "public_api.md"
    target.write_text(target.read_text(encoding="utf-8") + "\nBOGUS DRIFT LINE\n", encoding="utf-8")

    assert generator.check_drift(version) != 0


def test_check_tolerates_a_version_only_difference(generator, monkeypatch):
    """A contributor on a different installed version must get a content-drift signal, not a
    spurious failure from the version stamp alone."""
    version = insitupy.__version__
    generator.write_targets(version)

    other_version = "9.9.9-different"
    monkeypatch.setattr(insitupy, "__version__", other_version)
    assert generator.check_drift(other_version) == 0
